#
# How much each reward is reduced within RewardCoolDownInSeconds.
# First reward = 1.0, next 0.85, next 0.85*0,85, etc, until no reward for RewardCoolDownInSeconds seconds, where reward is restored to 1.0
#
RewardReduction: 0.85

#
# Time for reward reduction after latest reward.
#
RewardCoolDownInSeconds: 5

#
# Worlds where there is a penalty for dying
#
PenaltyOnDeathWorlds: [W_Hardcore, W_SurvivalFreebuild]

#
# Commands that should have a cooldown period
#
CoolDownCommands: ["/broadcast"]
CoolDownTimeInSeconds: [30]

#
# The cost of dying in one of the worlds in PenaltyOnDeathWorlds
#
CostOfDeath: 30.0

#
# Worlds where you can buy stuff
#
BuyWorlds: [W_SurvivalFreebuild]
#
# Chat channels. Used to leave all other channels.
#
ChatChannelsToLeave: [1, 2, 3, 4]

eithon:
  UseMarkUpForMessages: 1
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 2

commands:

  #
  # GiveCommand has 3 parameters: <player> (%s), <item> (%s), <amount> (%d)
  GiveCommand: give %s %s %d

  #
  # TakeCommand has 2 parameters: <player> (%s), <totalprice> (%f)
  TakeCommand: eco take %s %f
  
  #
  # LeaveChannel has 1 parameters: <channel name> (%s)
  LeaveChannel: ch leave %s

  #
  # LeaveChannel has 1 parameters: <channel name> (%s)
  JoinChannel: ch enter %s

messages:
  #
  # This message is broadcasted when someone logs in to the server for the first time
  # Parameters: <player name> (%s)
  #
  JoinedServerFirstTime: "[color=green]+ [/color][color=lightpurple]%s[/color] [color=darkaqua]joined for the first time![/color]"

  #
  # This message is broadcasted to members with rankup
  # Parameters: <player name> (%s)
  #
  PleaseWelcomeNewPlayer: "[subtitle/]Welcome [color=lightpurple]%s[/color] [color=white]to the server![/color]"

  #
  # Message after death cost
  #
  # Parameters: <cost> (%f)
  #
  PenaltyOnDeathMessage: Your death has resulted in a penalty of %.2f.

  #
  # Parameters: <money needed> (%f), <amount> (%d), <item> (%s), <current balance> (%f)
  YouNeedMoreMoney: You need %.2f to buy %d %s. You have %.2f.

  #
  # Parameters: <amount> (%d), <item> (%s)
  SuccessfulPurchase: You successfully purchased %d item(s) of %s.

  #
  # Parameters: -
  InventoryFull: Your inventory is full.  
  
  #
  # Parameters: <balance> (%f)
  CurrentBalance: Your balance is %.2f E-Coins.

  #
  # Parameters: <channel name> (%s)
  JoinedChat: You have joined chat channel %s.

  #
  # This message is displayed when someone tries to use a command again too fast
  # Parameters: <remaining time> (%s)
  #
  WaitForCoolDown: "In cool down. Remaining time: %s."
