name: EithonFixes
main: net.eithon.plugin.fixes.Plugin
version: 1.28
author: vanbrayne
softdepend: [Essentials, WorldEdit, EithonStats, KillerMoney]
depend: [EithonLibrary]
description: A Minecraft plugin for Eithon fixes
commands:
  eithonfixes:
    description: Fix things other plugins fail to do
    usage: /eithonfixes buy | balance | debug | rcadd | rcedit | rclist | rcdelete | rcgoto  | spadd | spedit | splist | spdelete | spgoto | restart | server | test
    permission-message: You don't have <permission>
permissions:
  eithonfixes.*:
    description: Gives access to all eithonfixes commands
    default: op
    eithonfixes.buy: true
    eithonfixes.balance: true
    eithonfixes.debug: true
    eithonfixes.rcadd: true
    eithonfixes.rcedit: true
    eithonfixes.rclist: true
    eithonfixes.rcset: true
    eithonfixes.rcgoto: true
    eithonfixes.rcdelete: true
    eithonfixes.spadd: true
    eithonfixes.spedit: true
    eithonfixes.splist: true
    eithonfixes.spgoto: true
    eithonfixes.spdelete: true
    eithonfixes.restart: true
    eithonfixes.test: true
    eithonfixes.server: true
    eithonfixes.canfly: true
  eithonfixes.buy:
    description: Access to /eithonfixes buy command
    default: op
  eithonfixes.balance:
    description: Access to /eithonfixes balance command
    default: op
  eithonfixes.debug:
    description: Access to /eithonfixes debug command
    default: op
  eithonfixes.rcadd:
    description: Access to /eithonfixes rcadd command
    default: op
  eithonfixes.rcedit:
    description: Access to /eithonfixes rcedit command
    default: op
  eithonfixes.rcset:
    description: Access to /eithonfixes rcset command
    default: op
  eithonfixes.rclist:
    description: Access to /eithonfixes rclist command
    default: op
  eithonfixes.rcdelete:
    description: Access to /eithonfixes rcdelete command
    default: op
  eithonfixes.rcgoto:
    description: Access to /eithonfixes rcgoto command
    default: op
  eithonfixes.spadd:
    description: Access to /eithonfixes spadd command
    default: op
  eithonfixes.spedit:
    description: Access to /eithonfixes spedit command
    default: op
  eithonfixes.splist:
    description: Access to /eithonfixes splist command
    default: op
  eithonfixes.spdelete:
    description: Access to /eithonfixes spdelete command
    default: op
  eithonfixes.spgoto:
    description: Access to /eithonfixes spgoto command
    default: op
  eithonfixes.restart:
    description: Access to /eithonfixes restart command
    default: op
  eithonfixes.test:
    description: Access to /eithonfixes test command
    default: op
  eithonfixes.server:
    description: Access to /eithonfixes server command
    default: op
  eithonfixes.nocooldown:
    description: Avoid cool down period between commands.
    default: op
  eithonfixes.canfly:
    description: Can fly even in freebuild mode
    default: op
