name: EithonFixes
main: net.eithon.plugin.fixes.Plugin
version: ${project.version}
author: vanbrayne
softdepend: [Essentials, WorldEdit, EithonStats, KillerMoney]
depend: [EithonLibrary]
description: A Minecraft plugin for Eithon fixes
commands:
  eithonfixes:
    description: Fix things other plugins fail to do
    usage: /eithonfixes buy | balance | debug | rc | sp | restart | server | test | freeze
    permission-message: You don't have <permission>
permissions:
  eithonfixes.*:
    description: Gives access to all eithonfixes commands
    default: op
    eithonfixes.buy: true
    eithonfixes.balance: true
    eithonfixes.debug: true
    eithonfixes.rc.add: true
    eithonfixes.rc.edit: true
    eithonfixes.rc.list: true
    eithonfixes.rc.set: true
    eithonfixes.rc.goto: true
    eithonfixes.rc.delete: true
    eithonfixes.sp.add: true
    eithonfixes.sp.edit: true
    eithonfixes.sp.list: true
    eithonfixes.sp.goto: true
    eithonfixes.sp.delete: true
    eithonfixes.restart: true
    eithonfixes.test: true
    eithonfixes.canfly: true
    eithonfixes.freeze.on : true
    eithonfixes.freeze.off : true
    eithonfixes.freeze.restore : true
    eithonfixes.freeze.list : true
  eithonfixes.buy:
    description: Access to /eithonfixes buy command
    default: op
  eithonfixes.balance:
    description: Access to /eithonfixes balance command
    default: op
  eithonfixes.debug:
    description: Access to /eithonfixes debug command
    default: op
  eithonfixes.rc.add:
    description: Access to /eithonfixes rc add command
    default: op
  eithonfixes.rc.edit:
    description: Access to /eithonfixes rc edit command
    default: op
  eithonfixes.rc.set:
    description: Access to /eithonfixes rc set command
    default: op
  eithonfixes.rc.list:
    description: Access to /eithonfixes rc.list command
    default: op
  eithonfixes.rc.delete:
    description: Access to /eithonfixes rc.delete command
    default: op
  eithonfixes.rc.goto:
    description: Access to /eithonfixes rc.goto command
    default: op
  eithonfixes.sp.add:
    description: Access to /eithonfixes sp.add command
    default: op
  eithonfixes.sp.edit:
    description: Access to /eithonfixes sp.edit command
    default: op
  eithonfixes.sp.list:
    description: Access to /eithonfixes sp.list command
    default: op
  eithonfixes.sp.delete:
    description: Access to /eithonfixes sp.delete command
    default: op
  eithonfixes.sp.goto:
    description: Access to /eithonfixes sp.goto command
    default: op
  eithonfixes.restart:
    description: Access to /eithonfixes restart command
    default: op
  eithonfixes.test:
    description: Access to /eithonfixes test command
    default: op
  eithonfixes.freeze.on:
    description: Access to /eithonfixes freeze on command
    default: op
  eithonfixes.freeze.off:
    description: Access to /eithonfixes freeze off command
    default: op
  eithonfixes.freeze.restore:
    description: Access to /eithonfixes freeze restore command
    default: op
  eithonfixes.freeze.list:
    description: Access to /eithonfixes freeze list command
    default: op
  eithonfixes.nocooldown:
    description: Avoid cool down period between commands.
    default: op
  eithonfixes.canfly:
    description: Can fly even in freebuild mode
    default: op
