name: EithonFixes
main: net.eithon.plugin.fixes.Plugin
version: 1.2
author: vanbrayne
softdepend: [Essentials, KillerMoney]
depend: [EithonLibrary]
description: A Minecraft plugin for Eithon fixes
commands:
  eithonfixes:
    description: Fix things other plugins fail to do
    usage: /eithonfixes buy | balance | join
    permission-message: You don't have <permission>
permissions:
  eithonfixes.*:
    description: Gives access to all eithonfixes commands
    default: op
    eithonfixes.buy: true
    eithonfixes.balance: true
  eithonfixes.buy:
    description: Access to /eithonfixes buy command
    default: op
  eithonfixes.balance:
    description: Access to /eithonfixes balance command
    default: op
  eithonfixes.join:
    description: Access to /eithonfixes join command
    default: op
  eithonfixes.nocooldown:
    description: Avoid cool down period between commands.
    default: op
